### ISSUE TITLE
Strange socketio error

### ISSUE THREAD

**Issue by vallettea** [anthill/city-core#85] opened 2015-01-06 18:35 UTC
on the server i saw this sometimes:

```
starting in mode dev
Server running on 9000

/home/queenant/city-core/node_modules/socket.io/node_modules/engine.io/lib/socket.js:338
      this.sentCallbackFn.push.apply(this.sentCallbackFn, this.packetsFn);
                               ^
RangeError: Maximum call stack size exceeded
    at Socket.flush (/home/queenant/city-core/node_modules/socket.io/node_modules/engine.io/lib/socket.js:338:32)
    at WebSocket.EventEmitter.emit (events.js:117:20)
    at /home/queenant/city-core/node_modules/socket.io/node_modules/engine.io/lib/transports/websocket.js:94:14
    at afterWrite (_stream_writable.js:274:3)
    at onwrite (_stream_writable.js:266:7)
    at Socket.WritableState.onwrite (_stream_writable.js:97:5)
    at Object.afterWrite (net.js:728:12)
error: Forever detected script exited with code: 8
error: Script restart attempt #1
starting in mode dev
Server running on 9000
```

we should have a look

**Comment by DavidBruant** [comment] 2015-01-14 13:18
dupe of #91

**Closed by DavidBruant** 2015-01-14 13:18 UTC
